name: NuGet
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Shimmer on version change
        id: publish_shimmer_nuget
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: Shimmer/Shimmer.csproj
          PACKAGE_NAME: Xeretis.Shimmer
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
      - name: Publish Shimmer.AspNetCore on version change
        id: publish_shimmer_aspnetcore_nuget
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          PROJECT_FILE_PATH: Shimmer.AspNetCore/Shimmer.AspNetCore.csproj
          PACKAGE_NAME: Xeretis.Shimmer.AspNetCore
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}